default:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }

start:
    path: /start/{size}/{mode}
    defaults: { _controller: "AppBundle:Default:start", size: 3, mode: human }

play:
    path: /play/{row}-{col}
    defaults: { _controller: "AppBundle:Default:play" }

end:
    path: /end
    defaults: { _controller: "AppBundle:Default:end" }

save:
    path: /save
    defaults: { _controller: "AppBundle:Default:save" }

restore:
    path: /restore
    defaults: { _controller: "AppBundle:Default:restore" }