default:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }

start:
    path: /start/{size}
    defaults: { _controller: "AppBundle:Default:start", size: 3 }

play:
    path: /play/{row}-{col}
    defaults: { _controller: "AppBundle:Default:play" }

end:
    path: /end
    defaults: { _controller: "AppBundle:Default:end" }